"""
pytest integration: read the host from configuration before collection, and verify declared suites ran.

``pytest --due-work-verify`` closes the gap between the static coverage check
and the test run. The scan counts a function as covered or exempt because a
declaration exists; this option fails the session unless every one of those
declarations also ran at least one case here — so a suite that is skipped by an
``importorskip``, deselected, or never collected cannot keep a function counted.

``pytest --due-work-record-findings`` prints, after the run, the ``Findings`` each
history would pin, ready to paste (see :mod:`due_work_harness.recording`); run it
without ``-n``, since the runs are recorded in the process that makes them.

``pytest --due-work-summary`` prints, after the run, what every generated suite
produced: each class's cases with their outcome, and each known gap's reason.
A contract class is empty in the source, so this is where a reader sees what
it generated and which declared gaps it reports as strict xfails.
"""

from importlib import import_module
from pathlib import Path

import pytest

from due_work_harness.coverage.config import load_config
from due_work_harness.coverage.scan import scan
from due_work_harness.host import Host, configure
from due_work_harness.recording import report, start_recording, stop_recording

VERIFY = "--due-work-verify"
VERIFY_PLUGIN = "due-work-verify"
SUMMARY = "--due-work-summary"
SUMMARY_PLUGIN = "due-work-summary"
RECORD = "--due-work-record-findings"
RECORD_PLUGIN = "due-work-record-findings"


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addini(
        "due_work_harness_host",
        "Dotted path 'package.module:attribute' of the due_work_harness Host to install; "
        "the attribute may be a Host or a zero-argument callable returning one.",
        default="",
    )
    group = parser.getgroup("due-work-harness")
    for flag, help_text in (
        (VERIFY, "fail unless every contract and exemption suite the coverage scan counts ran at least one case"),
        (
            RECORD,
            "print the Findings every history would pin, instead of checking the declared tables (run without -n)",
        ),
        (SUMMARY, "after the run, list every generated case by suite with its outcome, and each known gap's reason"),
    ):
        group.addoption(flag, action="store_true", default=False, help=help_text)


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line(
        "markers", "due_work: a case generated by due-work-harness (contract, safety, exemption and selection suites)"
    )
    # Under xdist, the controller receives every worker's reports and holds the verdict; a worker
    # sees only its share, and would rescan the whole project at its own session's end for nothing.
    worker = hasattr(config, "workerinput")
    if config.getoption(VERIFY) and not worker:
        config.pluginmanager.register(_SuitesRan(config), VERIFY_PLUGIN)
    if config.getoption(SUMMARY) and not worker:
        config.pluginmanager.register(_Summary(), SUMMARY_PLUGIN)
    if config.getoption(RECORD):
        # Histories run in the process that owns the database; under xdist that is a worker, whose
        # recorder the controller never sees, so recording would silently print nothing.
        if worker or config.getoption("numprocesses", default=None):
            raise pytest.UsageError(f"{RECORD} records in the process that runs the histories: run without -n")
        config.pluginmanager.register(_Recording(), RECORD_PLUGIN)
    path = config.getini("due_work_harness_host")
    if not path:
        return
    module_name, _, attribute = path.partition(":")
    assert attribute, f"due_work_harness_host must look like 'package.module:attribute', got {path!r}"
    target = getattr(import_module(module_name), attribute)
    host = target if isinstance(target, Host) else target()
    assert isinstance(host, Host), f"{path} did not produce a due_work_harness Host"
    configure(host)


class _SuitesRan:
    """Records which ``Test*`` classes ran a case, then holds every counted declaration to having run."""

    def __init__(self, config: pytest.Config) -> None:
        self.root = config.rootpath
        try:
            self.coverage = load_config(self.root)
        except ValueError as error:
            raise pytest.UsageError(f"{VERIFY}: {error}") from error
        #: (file, class) pairs with at least one case that executed.
        self.ran: set[tuple[Path, str]] = set()
        self.problems: list[str] = []

    def pytest_runtest_logreport(self, report: pytest.TestReport) -> None:
        # A case ran when its call phase executed (passed, failed or xfailed) or its setup failed;
        # a case skipped before its call never ran.
        executed = report.when == "call" or (report.when == "setup" and report.failed)
        parts = report.nodeid.split("::")
        if executed and len(parts) >= 3:
            self.ran.add(((self.root / parts[0]).resolve(), parts[1]))

    @pytest.hookimpl(tryfirst=True)
    def pytest_sessionfinish(self, session: pytest.Session) -> None:
        for qualified, disposition in sorted(scan(self.coverage).dispositions.items()):
            if disposition.how not in ("covered", "exempt"):
                continue
            relative, _, cls = disposition.where.rpartition("::")
            if ((self.coverage.root / relative).resolve(), cls) not in self.ran:
                self.problems.append(
                    f"{qualified} is {disposition.how} by {disposition.where}, which ran no case in this session: "
                    f"it was skipped, deselected or never collected, so nothing here proves the disposition"
                )
        if self.problems and session.exitstatus in (pytest.ExitCode.OK, pytest.ExitCode.NO_TESTS_COLLECTED):
            session.exitstatus = pytest.ExitCode.TESTS_FAILED

    def pytest_terminal_summary(self, terminalreporter: pytest.TerminalReporter) -> None:
        if not self.problems:
            return
        terminalreporter.section("due-work-harness: declared suites that did not run", red=True)
        for problem in self.problems:
            terminalreporter.line(f"  - {problem}")


class _Summary:
    """Collects the outcome of every generated case, then prints them by suite."""

    def __init__(self) -> None:
        #: suite (``file::Class``) -> [(outcome, case, gap reason)], in run order.
        self.suites: dict[str, list[tuple[str, str, str]]] = {}

    def pytest_runtest_logreport(self, report: pytest.TestReport) -> None:
        if "due_work" not in report.keywords:
            return
        if report.when == "call" or (report.when == "setup" and not report.passed):
            suite, _, case = report.nodeid.rpartition("::")
            reason = getattr(report, "wasxfail", "")
            if reason and report.skipped:
                outcome = "XFAIL"
            elif reason:
                outcome = "XPASS"
            else:
                outcome = report.outcome.upper()
            name = case.split("[", 1)[1][:-1] if "[" in case else case
            self.suites.setdefault(suite, []).append((outcome, name, reason))

    def pytest_terminal_summary(self, terminalreporter: pytest.TerminalReporter) -> None:
        if not self.suites:
            return
        terminalreporter.section("due-work-harness: what each suite generated")
        for suite, cases in self.suites.items():
            counts: dict[str, int] = {}
            for outcome, _name, _reason in cases:
                counts[outcome] = counts.get(outcome, 0) + 1
            tally = ", ".join(f"{counts[outcome]} {word}" for outcome, word in _WORDS.items() if outcome in counts)
            terminalreporter.line(f"{suite}: {tally}")
            for outcome, name, reason in cases:
                gap = f"  ({_shorten(reason)})" if reason else ""
                terminalreporter.line(f"  {outcome:<7} {name}{gap}")


#: Outcomes in pytest's own order and words.
_WORDS = {"PASSED": "passed", "FAILED": "failed", "SKIPPED": "skipped", "XFAIL": "xfailed", "XPASS": "xpassed"}


def _shorten(reason: str, limit: int = 110) -> str:
    return reason if len(reason) <= limit else reason[: limit - 1].rstrip() + "…"


class _Recording:
    """Turns findings recording on for the session, and prints what it recorded."""

    def __init__(self) -> None:
        self.recorder = start_recording()

    def pytest_terminal_summary(self, terminalreporter: pytest.TerminalReporter) -> None:
        if not self.recorder.histories:
            terminalreporter.line("due-work-harness: no history ran, so nothing was recorded")
            return
        terminalreporter.section(
            "due-work-harness: recorded findings (what the code does today: review before pinning)"
        )
        terminalreporter.write_line(report(self.recorder))

    def pytest_unconfigure(self) -> None:
        stop_recording()
