"""
pytest integration: read the host from configuration before collection, and verify declared suites ran.

``pytest --due-work-verify`` closes the gap between the static coverage check
and the test run. The scan counts a function as covered or exempt because a
declaration exists; this option fails the session unless every one of those
declarations also ran at least one case here — so a suite that is skipped by an
``importorskip``, deselected, or never collected cannot keep a function counted.
"""

from importlib import import_module
from pathlib import Path

import pytest

from due_work_harness.coverage.config import load_config
from due_work_harness.coverage.scan import scan
from due_work_harness.host import Host, configure

VERIFY = "--due-work-verify"
VERIFY_PLUGIN = "due-work-verify"


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addini(
        "due_work_harness_host",
        "Dotted path 'package.module:attribute' of the due_work_harness Host to install; "
        "the attribute may be a Host or a zero-argument callable returning one.",
        default="",
    )
    parser.getgroup("due-work-harness").addoption(
        VERIFY,
        action="store_true",
        default=False,
        help="fail unless every contract and exemption suite the coverage scan counts ran at least one case",
    )


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line(
        "markers", "due_work: a case generated by due-work-harness (contract, safety, exemption and selection suites)"
    )
    # Under xdist, the controller receives every worker's reports and holds the verdict; a worker
    # sees only its share, and would rescan the whole project at its own session's end for nothing.
    if config.getoption(VERIFY) and not hasattr(config, "workerinput"):
        config.pluginmanager.register(_SuitesRan(config), VERIFY_PLUGIN)
    path = config.getini("due_work_harness_host")
    if not path:
        return
    module_name, _, attribute = path.partition(":")
    assert attribute, f"due_work_harness_host must look like 'package.module:attribute', got {path!r}"
    target = getattr(import_module(module_name), attribute)
    host = target if isinstance(target, Host) else target()
    assert isinstance(host, Host), f"{path} did not produce a due_work_harness Host"
    configure(host)


class _SuitesRan:
    """Records which ``Test*`` classes ran a case, then holds every counted declaration to having run."""

    def __init__(self, config: pytest.Config) -> None:
        self.root = config.rootpath
        try:
            self.coverage = load_config(self.root)
        except ValueError as error:
            raise pytest.UsageError(f"{VERIFY}: {error}") from error
        #: (file, class) pairs with at least one case that executed.
        self.ran: set[tuple[Path, str]] = set()
        self.problems: list[str] = []

    def pytest_runtest_logreport(self, report: pytest.TestReport) -> None:
        # A case ran when its call phase executed (passed, failed or xfailed) or its setup failed;
        # a case skipped before its call never ran.
        executed = report.when == "call" or (report.when == "setup" and report.failed)
        parts = report.nodeid.split("::")
        if executed and len(parts) >= 3:
            self.ran.add(((self.root / parts[0]).resolve(), parts[1]))

    @pytest.hookimpl(tryfirst=True)
    def pytest_sessionfinish(self, session: pytest.Session) -> None:
        for qualified, disposition in sorted(scan(self.coverage).dispositions.items()):
            if disposition.how not in ("covered", "exempt"):
                continue
            relative, _, cls = disposition.where.rpartition("::")
            if ((self.coverage.root / relative).resolve(), cls) not in self.ran:
                self.problems.append(
                    f"{qualified} is {disposition.how} by {disposition.where}, which ran no case in this session: "
                    f"it was skipped, deselected or never collected, so nothing here proves the disposition"
                )
        if self.problems and session.exitstatus in (pytest.ExitCode.OK, pytest.ExitCode.NO_TESTS_COLLECTED):
            session.exitstatus = pytest.ExitCode.TESTS_FAILED

    def pytest_terminal_summary(self, terminalreporter: pytest.TerminalReporter) -> None:
        if not self.problems:
            return
        terminalreporter.section("due-work-harness: declared suites that did not run", red=True)
        for problem in self.problems:
            terminalreporter.line(f"  - {problem}")
